#!/bin/bash
TGTFILE=./FTCLocal

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd "${DIR}"
cd bin
echo "Welcome to FIRST Tech Challenge Live!" 	 

if [ "$(whoami)" == "root*" ]
then
    echo "Already a super user... launching software."
    echo "$TGTFILE"
    $TGTFILE
else	 
    echo "This application requires super user status."
    echo "If prompted, please enter in your account password."
    echo "sudo $TGTFILE"
    sudo $TGTFILE   	 
fi
read -p "Press enter to continue"
